name: CI

on:
  pull_request:
    branches: 
      - main
      - dev

jobs:
  test:
    name: Testing packages against our testing suite.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: npm install and test
      run: |
        cd quell-client
        pwd
        npm install
        npm test
        cd ../quell-server
        pwd
        npm install
        npm test
        cd ../quell-extension
        pwd
        npm install
        npm test
        
        
